services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/beauty_salon
      - SECRET_KEY=your_secret_key_here
      - PYTHONUNBUFFERED=1
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./:/app
    restart: always
    command: >
      sh -c "pip install -r requirements.txt &&
             mkdir -p app/static/uploads/services app/static/css app/static/js app/static/images &&
             python init_db.py &&
             python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=beauty_salon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: 